esphome:
  name: dfrobot-sht31
  friendly_name: DFRobot SHT31 Sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# oder bei ESP8266:
# esp8266:
#   board: nodemcuv2

# --- WLAN ---
wifi:
  ssid: "FASW-IN"
  password: "Wilkommen"
 

# --- Logging & API ---
logger:
api:
ota:
 platform: esphome

web_server:
  port: 80

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  frequency: 100kHz

sensor:
  - platform: sht3xd
    # Wenn nicht gefunden wird: hier auf 0x45 ändern und nochmal testen
    address: 0x44
    temperature:
      name: "SHT31 Temperatur"
      accuracy_decimals: 1
    humidity:
      name: "SHT31 Luftfeuchtigkeit"
      accuracy_decimals: 1
    update_interval: 15s